### ISSUE TITLE
Curator job fails for hard coded jobs 

### ISSUE THREAD

**Issue by himmatb** [openshift/origin-aggregated-logging#1608]
Hi,

Openshift 3.10 version.

 I need your suggestion for issue currently I am facing with  Curator to maintain retention period for specific logs and keep default for all other project :

Below is configuration file for curator : 
```
# uncomment and use this to override the defaults from env vars
.defaults:
  delete:
    days: 10
  runhour: 12
  runminute: 30

abcdef:
  delete:
    days: 30

xyzabc:
  delete:
    days: 30
```
after keeping above configuration, I am getting below error :

INFO:__main__:No indices matched provided args: {'regex': '(^project\\.abcdef\\..*$|^project\\.xyzabc\\..*$)', 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': None, 'time_unit': 'days', 'timestring': '%Y.%m.%d', 'exclude': (), 'older_than': 30, 'all_indices': False}

I want to keep logs for specific project like abcdef and xyzabc to 30 days and other porject as default 10 days .

How can achieve above scenario, this is very important us to extend retention period  for two project for now, as we are facing escalation so we need to maintain these logs for 30 days at-least.

can you please provide helpful instruction to fix this  challenge.

Thanks in advance!!,
