### ISSUE TITLE
OSE_ES_VER version update to 5.6.13.6 breaks prometheus monitoring

### ISSUE THREAD

**Issue by Reamer** [openshift/origin-aggregated-logging#1686]
Hi,

i noticed with the last version([Current last Version](https://github.com/openshift/origin-aggregated-logging/commit/87e45f633ffe820a94943024e51000a54ae63f67)) in [release-3.11](https://github.com/openshift/origin-aggregated-logging/commits/release-3.11) branch the Elasticsearch monitoring is broken.

I built every week new images based on release-3.11 branch. The monitoring with the image from the last week works great.
With the current image I get following error.
```
[2019-07-09T12:00:41,822][INFO ][c.f.s.c.PrivilegesEvaluator] No cluster-level perm match for User [name=system:serviceaccount:openshift-monitoring:prometheus-k8s, roles=[gen_user_647a750f1787408bf50088234ec0edd5a6a9b2ac, gen_kibana_647a750f1787408bf50088234ec0edd5a6a9b2ac]] [IndexType [index=_all, type=*]] [Action [[cluster:monitor/prometheus/metrics]]] [RolesChecked [gen_kibana_647a750f1787408bf50088234ec0edd5a6a9b2ac, gen_user_647a750f1787408bf50088234ec0edd5a6a9b2ac]]
[2019-07-09T12:00:41,822][INFO ][c.f.s.c.PrivilegesEvaluator] No permissions for {}
```
After [reverting last commit](https://github.com/Reamer/origin-aggregated-logging/commit/f9acd9c500e583ece730d6391ebfffa0b44e190a) monitoring works again.

I made a [diff](https://github.com/fabric8io/openshift-elasticsearch-plugin/compare/openshift-elasticsearch-plugin-5.6.13.5...openshift-elasticsearch-plugin-5.6.13.6) of the OpenShift ElasticSearch plugin (OSE_ES), but didn't found anything suspicious.

Maybe it's not the plugin, but the changes in elasticsearch/sgconfig/sg_action_groups.yml. I didn't test it.

I hope, that somebody will find the bug.

Best Regards
Reamer

**Comment by jcantrill** [comment]
@Reamer What call are you making to get metrics?  I would like to introduce a test to cover regressions

**Comment by Reamer** [comment]
Hi @jcantrill 
As mentioned, I'm using Prometheus to get metrics. I added an additional [ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitor) into namespace `openshift-monitoring`

My current ServiceMonitor:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: elasticsearch
  name: elasticsearch
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    path: /_prometheus/metrics
    port: proxy
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      insecureSkipVerify: true
  jobLabel: elasticsearch-app
  namespaceSelector:
    matchNames:
    - openshift-logging
  selector:
    matchLabels:
      k8s-app: elasticsearch
```

I also added a label to `logging-es-prometheus` via
```
oc label service logging-es-prometheus k8s-app=elasticsearch
```

But you can simulate the http request to elasticsearch metics endpoint with a simple curl command.
Using curl in prometheus container. Get bearer token from `/var/run/secrets/kubernetes.io/serviceaccount/token`
```
curl -k -H "Authorization: Bearer [Your Token]" https://10.128.1.x:4443/_prometheus/metrics
```

This request will hit `origin-oauth-proxy` on port 4443. Because of `prometheus-metrics-viewer` role the request is send to elasticsearch via `https://localhost:9200` on endpoint `_prometheus/metrics`

My current scrape config in prometheus:
```
scrape_configs:
- job_name: openshift-monitoring/elasticsearch/0
  honor_labels: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /_prometheus/metrics
  scheme: https
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - openshift-logging
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_k8s_app]
    separator: ;
    regex: elasticsearch
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: proxy
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_elasticsearch_app]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: proxy
    action: replace
```
