### ISSUE TITLE
Curator picks runhour in curator_settings (/etc/curator/settings) as local timezone instead of UTC on OSE

### ISSUE THREAD

**Issue by xiazhao2015** [openshift/origin-aggregated-logging#182]
The below issue is found on v3.2.1 enterprise images:

If set UTC time given by
`date -u +%H`
into runhour in curator_settings, curator picked the time for log deletion as local time zone, and triggered log deletion then, but I expect curator to consider the time in settings as UTC time and trigger it in correct time spot, that is:

My current local time is:
```
$ date +"%b %d %H:%M:%S"
Jun 23 05:48:43
```

and the equivalent UTC time is:
```
$ date -u +"%b %d %H:%M:%S"
Jun 23 09:48:34
```

If I set:

```
.defaults:
  delete:
    days: 30
  runhour: 09
  runminute: 48
project-dev:
  delete:
    days: 1
```
...

The log deletion will not be trigger immediately, I can only get it work by giving the local hour into curator_settings, this worked immediately:
`runhour: 05`
