### ISSUE TITLE
Curator ignores more than one project with same time and time unit

### ISSUE THREAD

**Issue by richm** [openshift/origin-aggregated-logging#196]
if you have curator configured with more than one project with the same time and time unit:
```
project-dev:
  delete:
    days: 7
project-qe:
  delete:
    days: 7
```
Only 1 of these will be processed.  The problem is that we are passing in multiple `--prefix $project` to the curator binary and it ignores all but 1.
