### ISSUE TITLE
OCP 3.11 - How can we grant non-cluster-admin-users access to index pattern project.*

### ISSUE THREAD

**Issue by MastanaGuru** [openshift/origin-aggregated-logging#1984]
As users have access to only their projects, a user has to build a dashboard for each of their project. I am creating some generic dashboards which uses index-pattern project.*  How can we grant project.* access to all non-cluster-admin users.
Looking at  #1603, I tried updating sg_roles.yml and sg_roles_mapping.yml as below and ran the es_seed_acl which did not give any error. But when I login to Kibana, get a blank screen with only the sidebar.

sg_roles.yml
```
sg_role_users:
  indices:
    '?project?*':
      '*':
        '*':
          - ALL
```

sg_roles_mapping.yml
```
sg_role_users:
  users: 
    - '*'
```

**Comment by jcantrill** [comment]
Consider modifying the kibana index mode to be shared_non_ops:

https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_logging_elasticsearch/defaults/main.yml#L42
https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_logging_elasticsearch/vars/main.yml#L4

**Comment by MastanaGuru** [comment]
@jcantrill, after the index mode change, do we still need to make above changes to sg_roles and sg_roles_mapping ?

**Comment by MastanaGuru** [comment]
@jcantrill, I made the changes in main.yaml and ran the playbook. I can see the changes in the elasticsearch.yml in the configmap
```
openshift.config:
  project_index_prefix: project
  time_field_name: '@timestamp'
  use_common_data_model: true
**openshift.kibana.index.mode: shared_non_ops**
openshift.operations.allow_cluster_reader: false
openshift.searchguard:
  keystore.path: /etc/elasticsearch/secret/admin.jks
  truststore.path: /etc/elasticsearch/secret/searchguard.truststore
```
but a non-cluster-admin is still not seeing the project.* index pattern.
