### ISSUE TITLE
Logging dump script appears to be missing info about kibana container

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#776]
Please see the output of:

https://bugzilla.redhat.com/attachment.cgi?id=1350461

I was looking for Kibana container info and only saw details about the proxy

**Comment by ruromero** [comment]
In file ./project/pods/logging-kibana-1-wzgr5 you can see the details of the container. Is that what you mean?
```
  - env:
    - name: ES_HOST
      value: logging-es
    - name: ES_PORT
      value: "9200"
    - name: KIBANA_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: kibana
          divisor: "0"
          resource: limits.memory
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-kibana:v3.5
    imagePullPolicy: IfNotPresent
    name: kibana
    resources:
      limits:
        memory: 736Mi
      requests:
        memory: 736Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
        - SYS_CHROOT
      privileged: false
      runAsUser: 1000050000
      seLinuxOptions:
        level: s0:c7,c4
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /etc/kibana/keys
      name: kibana
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: aggregated-logging-kibana-token-40rvf
      readOnly: true
```
